INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('Test@Test.com', 'Test', 'Test User')
     , ('Test@Test.com', 'Test', 'Test User')
     , (' cillum dolore eu f', 'ng elit, sed ', 'at nulla par')
     , ('mmodo consequa', 'et,', 'e eu f')
     , ('ehende', 'aborum.L', 'pta')
     , ('erunt moll', 'ation ullamco l', 'trud exercit')
     , ('idunt ut labore et dolore mag', 'iat null', 'r sit amet, consectetur adip')
     , ('minim veniam, quis nostrud', 'llamco laboris n', 'iam, q')
     , ('ad minim veniam', 'aborum.Lor', ' voluptate ')
     , ('mco laboris nisi ut aliquip e', 'aliqu', 'im veniam, quis nostrud')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('proident', 'reprehenderi', ' occaecat cupidatat ')
     , ('ion u', 'omm', ' anim i')
     , ('psum dolor', 'tetur adipisc', 'g elit')
     , ('sse cillum dolore eu ', 'pidatat non ', 'ulpa q')
     , ('olor in repre', 'c', ' nostru')
     , ('on ullam', 'ui', 'on')
     , ('bore et dolore', 'pa qui off', 'e velit esse cillum do')
     , ('. D', 'enderit in v', 'ec')
     , (' ex ea commodo c', 'abore et dolore ', 'strud exe')
     , ('dolor sit amet, consectetur ad', ' volup', 'f')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('nderit in v', 'ore eu fugia', ' laboris nisi ut aliquip e')
     , ('culpa qui ', 'aute irure', 'scing elit, sed do eiusmod t')
     , (' Excepteur sint occaecat c', ' eiusmod tem', 'pariatur. Excep')
     , ('empor incididunt', 'ur si', 'mollit ani')
     , ('dent, sunt in culpa', 'didunt ', 'or incididunt ut labore et ')
     , ('r', 'lor sit amet,', 'x')
     , ('epteur si', 'idunt ut labore ', 'aute irure dolor')
     , (' ut labore et do', 'qua. Ut en', 'od tempor incididunt ut labo')
     , ('ident, sunt in', 'tempor i', 'liqua. Ut e')
     , ('nt in cul', 'adipis', 'it anim id est lab')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('m dolore e', 't. ', ' ut lab')
     , ('rci', 'iqua. Ut ', 'ent, sunt in culpa qui offic')
     , ('a paria', 'r in repreh', ' Duis aute irure dolo')
     , ('rum.Lorem i', '. Excep', 'tation ullamco laboris n')
     , ('lpa qui officia dese', ' mo', 'ur')
     , ('t labore et dolore ', 'et do', 's aute irure d')
     , ('lore magna aliqua. Ut enim a', 'nim', 'scing elit, sed d')
     , (' vo', 'ecat cupidata', ', sunt in')
     , ('mollit anim id est lab', 'amco labori', 't nulla pariatur. Excepteur si')
     , ('at nulla pariat', ' nisi ut ali', ' ea commodo consequa')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('od tempor incididunt', 'ullamco laboris ', 't esse cillum dolore eu')
     , (' irure dolor in re', ' sint ', 'ore eu fugiat n')
     , ('lum dolore ', 'r s', 'ididunt ut labore et dolor')
     , ('cons', 'modo ', 'etur ad')
     , ('um dolor sit amet, consecte', 'magna aliqua.', 'u fug')
     , ('at nulla ', 'minim veniam,', 'consectetur adipiscin')
     , ('itation ullamco laboris', 'lore e', 'or')
     , ('r a', ' consectetur ad', 'ipsum do')
     , ('occaecat cupid', 'eru', 'nt, sunt in culpa ')
     , ('t mollit anim i', ' labore', 'aliquip ex ')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('mmodo consequat. Duis aute ir', 'smod tempor inc', 'onsequat. Duis a')
     , ('nt ut la', 'ore et', ' ex ea commodo conse')
     , ('mco laboris nisi ut aliquip ex', 'se cil', 'ut labore et dolor')
     , ('atur. Exce', 'proident, ', 'lor sit')
     , ('strud exerci', ' nulla pariatu', 'sum dolor sit amet, cons')
     , ('uis nostrud exerci', '. Excepteur sin', 'rud exercitation ullamco ')
     , ('r sit amet, consectetur ad', ' ', ' qui officia ')
     , (', quis nostrud ', 'u', 'r sit')
     , ('in culpa qui offici', 'um dolor s', ' ut aliquip ex ea com')
     , ('ccaecat cupida', 'liquip e', 'laborum.Lorem ipsum d')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('. Ut e', 'fficia deser', 'runt mollit')
     , ('s nostrud exercitation ulla', 'ic', 'tion ullamco laboris nisi ')
     , ('t', 'r ', 'at non proident, su')
     , ('eprehenderit in volu', 'o laboris nisi u', 'rure d')
     , ('ccaecat cupidatat non', 'ore eu fugiat ', 'ur sint occaecat cu')
     , (' ani', 're et d', 'eprehenderit in voluptate')
     , ('m dolor sit ', 'amco labo', 'ng elit, ')
     , (' sunt in culpa qui offi', 't enim ad', 'e dolor in reprehenderit')
     , ('sequat. Duis aute irure dol', 'agna aliqua. ', 'cia deserunt mollit anim')
     , ('ud exercitation ullamco ', 'rehenderit in', 'um dolor sit a')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('aborum.Lorem ipsum dolor sit a', ' sed do eiusmod', 'unt ut labore et dolore m')
     , ('ipsum dolor sit amet', 'qu', 'illum dolo')
     , ('uis aute ir', 'im id ', 't in culpa qui officia deseru')
     , ('n repreh', 'iat', 'p ex ea commodo c')
     , ('it, sed do eiusmod tempor inci', 'o ', 'a ')
     , (' comm', 'enim ', 'empo')
     , ('uis nostrud exerc', '.Lorem ipsum dol', 'it esse cillum dolore e')
     , ('qua. Ut enim ad minim veni', 'pariatur', 'iat nulla pariatur. Excepteur')
     , ('g elit, sed do ei', 'au', 'lor sit amet, con')
     , ('ipsu', 't cupidat', 'officia des')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('uip ex ea commodo consequat.', 're et dolo', 'it amet, consec')
     , ('amco laboris nisi ut ', ', quis nostrud ', 'pa qui officia deserunt moll')
     , ('ididunt ut labor', 'a', 'derit in')
     , ('lit esse cillum dolore eu fu', 'tat non pr', 'culpa qui officia deserunt m')
     , ('u', 'iusmod tempo', '.Lore')
     , ('do ', 't nulla', 'ollit anim id est laborum.Lore')
     , ('culpa qui officia des', 'gna aliqua. Ut e', ' vel')
     , ('citation ', 't l', '. Ut enim ad minim veniam, qu')
     , ('ommodo consequat. Duis aute', 'caecat cupidatat', 'nt mollit anim')
     , (' aliqua. Ut enim ad mini', 'lamco la', 'e cillum d')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('cia deserunt mollit a', 't in culpa ', 'aborum.Lorem ips')
     , ('commodo consequat', 'l', 'nderit in voluptate ve')
     , ('etur adipiscing elit', 'tation ullamco ', 'anim id est laborum.Lorem')
     , ('iatu', 'ate', 'ur adipisci')
     , ('d ', 'icia', 'riatur. Exce')
     , ('oident, sunt in cul', 'anim', 'dolor in reprehenderit in vo')
     , ('m dolo', ' ipsum dolor', ' esse cillum dolore eu fug')
     , ('na', ' aliqua. U', 'nt ')
     , ('e velit ', 'nisi ut aliqu', ' tempor inci')
     , ('ui offici', 'r', 'datat non pr')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('gna aliqua. Ut enim ad minim', 'dent, sun', 'nulla pariatu')
     , ('sequat. Duis aute iru', 'olor', 'se cillum do')
     , ('on proident, ', 'officia', 're et dolore m')
     , ('m ad minim veniam, quis', 'iam, qui', 'u ')
     , (' ', 'on ulla', 'am, quis nostrud ')
     , ('nisi ut aliquip ex', 'it esse ci', ' aliquip ex ea commo')
     , ('teur sint occaecat cupidata', 'enim ad minim', 'giat nulla pari')
     , ('cididunt ut labore et ', 'or sit ame', 'empor incididunt ut lab')
     , ('it in volup', 'd est l', 't cupidatat non proident, sun')
     , ('ficia deserunt mollit anim', 'im ad ', 're et dolore magna ali')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('a paria', ' e', 'im veniam, quis nostrud exerci')
     , ('atat non proident', ' mollit ani', 'sint occae')
     , ('xercitation ullamco', 't ', 'int occaecat cupidata')
     , ('ma', 'pidatat non ', ' ut aliquip ex ea commodo con')
     , ('a deserunt mol', ' et dolore mag', 'e')
     , ('ariatur. Excepteur sint occa', 'a', 'it, sed do eiusmod tempor')
     , ('qui officia deserunt mollit an', 'i officia de', 'sequat.')
     , (' occaecat cupidatat non p', 'gna a', 'sum dolor sit amet')
     , ('mollit anim i', 'nim', 'eiusmod temp')
     , ('pariatu', 'nim a', 'lamco la')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('um dolor sit amet, consecte', 're ', 'incididunt ut la')
     , (' Excepte', 'xercita', 'labore et dolore m')
     , ('lpa qui officia deserunt ', 'xcepteur sint', ' Duis aute irure do')
     , ('erunt ', ' ', 'ipiscing elit, sed do eiu')
     , ('dipiscing elit, sed do e', 'rure dolor ', 'n reprehenderit in volupta')
     , ('ccaecat cupidatat non proid', 'uis nostrud ex', ' do')
     , ('oluptate velit esse', 'n voluptate ', 'boris')
     , ('ollit anim id est laborum.Lo', 'a', 'xercitation ull')
     , ('te velit esse cillu', 'eniam, quis ', 'anim id est laborum.Lorem')
     , ('rem ipsum dolor sit amet', 'it, sed do', ' fugia')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('velit esse cillum dolore eu f', 'nt i', 'xercita')
     , ('ectetur adipiscing elit, sed d', ' fugiat nu', 'rud exercitation ullamco la')
     , ('a', 'ficia deserunt', 'tion ullamco')
     , ('ad', 'empor ', 'm, quis nostrud exerc')
     , ('etur adip', 'elit esse cil', 'it esse cillum dolore')
     , ('lum dolore eu ', ' des', 'velit esse cillum dolore ')
     , ('por incididunt ut labore e', 'do eiusmod t', 'sectetur adip')
     , ('lup', 's nostrud exe', 'sse cillum dolore eu fugiat nu')
     , ('co lab', 'aboris nisi ut', 'laborum.Lorem ip')
     , ('o eiusmod te', 'strud exe', ' proident, sunt in cu')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('ore eu fugiat n', 'ia deserunt mol', 'runt mo')
     , ('pisci', 'i', 'ommodo consequat. Du')
     , ('runt mollit a', 'tempor', 'usmod tempor incididunt u')
     , (' cupidatat non proident, su', 's aute irur', 'te ve')
     , ('s ', 'voluptate veli', 'sint occaecat cupidatat non p')
     , ('d exer', 'serunt moll', 'ollit anim id')
     , ('re dolor in repr', 'consequa', 'ullamco laboris nisi ut a')
     , ('non proident, sunt', 't anim i', 'o eiusmod tempor incididunt ut')
     , (' ', 'por incididunt u', 'psum dolor sit amet, consect')
     , ('is nisi ', 'tat n', 'or i')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('up', 'm id est', 'am, quis nostrud exercitati')
     , (' nisi ut aliquip', 'lum', 'am, qui')
     , ('iqua. Ut enim ad minim', 'a aliqua. Ut en', ' incididunt ut labo')
     , ('culpa qui officia d', 'sint occaec', 'iscing eli')
     , ('a. U', ' ipsum d', 'ncididunt ut')
     , ('ncididunt ut la', 'm dolore', 'unt ut labore et ')
     , ('dolore eu fugi', 'nisi ut aliqu', ', quis nostrud e')
     , ('m ad minim veniam', 'o', 'or incid')
     , ('llit anim id e', ' esse cill', 'lore eu fu')
     , ('nsectetur adip', 'labore e', 'ci')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('e dolo', 'tur adipi', 'psum dolor sit am')
     , ('unt ut labore et dol', ' ea com', 'm')
     , ('sed do e', 'etu', 'na a')
     , ('od te', 'ing elit, sed do', 't occaecat cupida')
     , ('teur', ' irure dolo', 'd')
     , ('unt in culpa qui off', 'riatur. ', ' do eiusmod tempor ')
     , (' cillu', 'officia deserun', 'sed do eiusm')
     , ('tion ullamco la', 'tetu', 'pidatat n')
     , ('eur sint occaecat c', 'im ', 'em ipsum dolor sit amet,')
     , (' aliquip ex ea commodo c', 'co labor', 'at cupidatat no')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('l', 'epteur ', 'irure dolor in r')
     , ('ati', 'usmod temp', 'atat non proident, sunt in cul')
     , ('est laborum.Lorem ipsum', ' nos', ' sit amet, conse')
     , ('it amet', 't in cu', 'lor ')
     , ('minim veniam, qui', 'xcepteur si', 'u fugia')
     , ('o consequat. Duis aute irur', 'et, conse', 'fficia deserunt mollit anim id')
     , ('ca', 'tur.', ' voluptat')
     , ('e cillum dolore', ' ni', 'ip ex ea commodo c')
     , ('e irure dolor in reprehenderi', 'is n', 'giat nulla')
     , ('qua. Ut enim a', 'oris nisi ut ali', 'u')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('ua', 'mod tempor incid', 'abore et dolore magna aliq')
     , ('on proident, sunt in culp', 'at', 'o')
     , ('cupidata', 'ris nisi ut ', 'i offici')
     , ('caecat cupidat', 'e magn', 'pa ')
     , (' labore et dolore magna ', 'e dol', 'e et dolore magna aliqua. U')
     , ('ad minim veniam, quis no', ' et', 'n reprehenderit i')
     , ('ng elit, sed do eius', 'is nisi ut ali', 'pidatat non proident, sunt in')
     , ('dipiscin', 't anim id est l', 'or s')
     , (' quis nostrud exercitation ull', 'dunt ut la', 'nostrud')
     , ('unt ut labore et do', 'anim i', 'r in r')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' et dolore magna aliqua', 'isc', 'consequat. Duis')
     , (' officia des', 'or incididun', ' nulla paria')
     , ('mc', 'nt occaecat cup', ' esse cillum dolore')
     , ('. Ut enim ad min', 'it, sed do', 'xcepteur si')
     , ('p ex ea commodo consequat', 'cepteur si', 'pa qui offic')
     , ('fficia deserunt mollit ', 'adipiscing elit', '. Ut e')
     , ('r sint occaecat cupida', ' quis nostrud e', 'dolor in reprehenderit in vol')
     , ('teur sint occaecat cu', 'it anim', 'runt mollit anim id e')
     , ('it anim id est laboru', 'derit ', 'ariatur. Excepteur sin')
     , ('. Excepteur sint occaecat c', 'labore et d', 'on proident, sunt in')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' qui officia deseru', 'idunt ut labore ', 're eu fugiat nulla paria')
     , ('i ut aliquip ex ea co', 'rud exerci', ' sunt in culpa qui offi')
     , ('rum.Lo', 'd exer', 'nsequat. Dui')
     , ('t cupidatat non proident, sun', 'stru', 'it amet, consectetur adipiscin')
     , ('t non proident, sunt in culpa ', 'itati', 'empor incididun')
     , (' non proi', 'um dolore eu', ' exercitation ul')
     , ('magna aliqua. Ut e', 'xcepteur sint o', ' Excep')
     , ('la pariatur. Excepteur s', 'd', ' an')
     , ('nt in culpa qui o', 'iden', 't. ')
     , (' ', 'qui offi', 'in reprehender')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('agna aliqua. Ut enim ad', ' do eiusmod te', 'ex ea')
     , (' ven', ' tempor', 'nderit in voluptate velit ess')
     , ('aliqu', ' eiusmo', 'e et dolore magna aliqua. Ut ')
     , ('m veniam, quis nostrud ex', ' ', ' dolore magna aliqu')
     , ('t in voluptate velit esse ', 'smod tempor i', 'prehenderit in v')
     , ('i officia deseru', 'la pariatur.', 'quat. Duis aute irure dol')
     , ('boris n', 'mmodo consequ', 'uat. Duis aute ')
     , (' sit amet, co', 'lor', 'm ad m')
     , ('cupidatat non proi', 'unt in culpa q', ' amet, consect')
     , ('lit anim id est laborum', 'r', 'ostrud exercitat')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('p', 'et dolore magna ', 'ur. Excepteur sin')
     , ('t, ', 'll', 'x ea c')
     , ('olor ', 'at. Duis aute i', 'cillum dol')
     , ('in rep', 'scing elit,', 'por in')
     , ('ipsum dolo', 'pidatat ', 'nim id est laborum.Lorem ipsum')
     , ('velit esse cill', 'niam, quis', 'u')
     , ('si', 'equat. Du', 'irure dolor in reprehende')
     , ('it esse cillum d', ' Excep', 'si ut aliquip ex ea comm')
     , ('cat cupidatat non', 'et dolore', 'derit in voluptate v')
     , ('illum dolore ', 'r', 'n culpa qui off')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('nulla pa', 'u', 'minim veniam, quis nostrud ')
     , ('laborum.L', 'is ', 'giat nulla pariatur. Ex')
     , ('i officia deserunt mollit ani', 'ip', 'prehenderit in volu')
     , ('e cillum dolore eu fugiat nul', 'nsectetur adipis', 't nulla pa')
     , ('nsectetur adipiscing elit, s', 'rud exercit', 'n proident, sunt ')
     , ('quip ex ea commodo con', 'ur. Excepteur si', 'eu fugiat nulla pariatur. Exce')
     , ('nt in culpa ', ' esse cillum do', 'on proident, sunt ')
     , ('t ut labo', 'l', 'veniam, quis nostrud')
     , ('nsectetur adipiscing eli', 'a. Ut enim', 'd te')
     , ('ad', 'dolore eu fugia', 'is nostrud exercitation ')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('equat. Duis aut', 'serunt mollit a', 'od tempor incididu')
     , ('gna aliqua. Ut enim ad', 'el', 'lit, s')
     , ('qui off', 'teu', 'pariatur. Except')
     , ('iscing elit, sed ', 'Lorem ipsum do', 'adipiscing elit, sed do eius')
     , ('ion', 'e cillum d', 'ud exercitatio')
     , ('oluptate velit esse c', 'culp', 'nderit in volupta')
     , ('tate velit esse cillum dolor', ' sunt in culp', 'lamco laboris ni')
     , (' non p', ' ullamco labori', 'Ut enim')
     , ('sint oc', 'n', 'n')
     , ('i officia deserunt', 't occaecat ', 'dolor in rep')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('ea commodo co', 'Ut ', 'iusmod tempor inci')
     , ('ip ex ea commodo consequ', 'pteur sin', 't, se')
     , ('t dolore magna aliqua. Ut', 'inim veniam, qu', 'oident, ')
     , (' dolor sit ame', ' anim', '. Ut enim ad m')
     , ('rud exercitation u', 'amet, conse', ' laboris nisi')
     , (' sit amet, consectetur adip', 'dolore eu fugi', 'enderit in vol')
     , ('re dolor in reprehender', 'm dolore eu fug', 'ecat cup')
     , ('giat nulla pari', 'ris nis', ' nulla ')
     , ('mod tempor in', 'iatur. E', 'e eu fugiat nulla pariatur.')
     , (' do eiusmod', 'rure do', ' consectetur adi')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('abore et dolore magna al', 'n reprehend', 'occaecat c')
     , ('u fugiat nulla pariatur', ' es', 'fic')
     , ('m v', ' tempor i', 'nt ut l')
     , ('xercit', 's nisi ut aliqui', 'r. Excep')
     , ('uip ex ea commodo consequa', 'modo consequ', 'co laboris ')
     , ('serunt mollit anim ', 'pi', 'lit anim id est laborum.Lor')
     , ('ectetur a', 'r adipiscing ', 'ctetur adipiscing elit, sed do')
     , (' fugiat nulla pariatur.', 'cillum dolore eu', ' esse cill')
     , (' cons', 'd do eiusmod ', 'dolore eu fugiat nulla ')
     , ('cupidatat', ' adipiscing ', ' quis nostrud exerci')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('tur. Excepteu', ' deserunt ', 'niam, quis nostrud')
     , ('ollit anim id e', 't. Duis aute', 's nisi u')
     , ('a commodo conse', 'rure ', 'oris nisi ')
     , ('magna aliqua.', 'iusmod tempor in', 'in')
     , ('a qui officia ', 'psum', ', consect')
     , ('ffi', 'ed do eiu', 'e cillum dolo')
     , ('dolor in reprehe', 'xc', ' laboris nisi ut aliquip ex e')
     , ('lit, sed do eiusmod t', 'r a', 'ns')
     , ('e et dolore magna al', 'ent, sun', 'elit, sed do eiusmod t')
     , ('sse cillum', 'strud ', 'e')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('at nulla pariatur. Excepteur ', ' e', 'nulla pariatur. Excepte')
     , ('adipiscing elit, sed do ', 'n', 'at ')
     , ('sse cillum dolore eu fugiat ', 'eprehenderi', 'labore et d')
     , ('or in repreh', 't', 'nim id est laborum.Lor')
     , ('a. Ut en', '. Duis aute iru', 'onsequat. Duis aute irure dolo')
     , ('ta', 're et dolore mag', ' mollit a')
     , ('ommodo conse', 'aborum.Lorem ip', 'b')
     , ('datat non proident', 'olore magna al', 'onsequat. Duis aute iru')
     , ('elit, s', 'e dolor i', 'd exercitation ullamco labor')
     , ('ccaecat ', ' proident, su', 'amco labo')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' tempor incididunt ut la', 'm ve', 'r ')
     , ('exercitation ', ' ', 't l')
     , ('offi', 'epteur si', 'llit anim id est la')
     , (' nostrud exerci', 'scing eli', 'rem ipsum dol')
     , (', sunt in culpa qui of', 'ullamco la', 'deserunt mollit anim id est ')
     , ('cing elit, s', 'cepteur s', 'oident, sunt in culpa q')
     , ('on ullamco laboris nisi ut ali', 'ididunt ut l', 'dolor in reprehenderit in volu')
     , ('lit, sed do eiusmod t', 'culpa qui offic', 't, sed d')
     , ('consectetur', 'abore', 'n')
     , ('uis nostrud exercitation', 'unt mollit ani', 'n voluptate velit esse cil')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' ad m', 'int occaec', 'ipsum')
     , ('olor sit amet, consec', 'ulpa qui off', 'proident, sunt in cu')
     , ('.Lorem', 'st', 'rit in voluptate velit e')
     , ('adipiscin', 'rud exe', 'aute irure dolor in')
     , ('tur. Excepteur si', 'a. Ut', 't, sed do eiusmod tem')
     , ('or sit amet, consectetur ', 'm', 'nsequat. D')
     , ('n culpa qui officia dese', 'olor in repr', 'int occaecat cupidatat ')
     , ('n proident,', 'ullamco labo', 'anim id est laborum.L')
     , (' eu fugiat nulla pariatur.', 're et dolore', 'ullamco laboris nisi u')
     , ('re magna a', ' id e', 'ehenderit in v')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('ion ullamco laboris n', 'or sit a', 'quip ex ea commodo consequat')
     , ('a deserunt mollit anim ', 'uat. Duis ', 'unt mollit anim')
     , ('e eu fugiat nulla paria', 'im id est labo', 'pida')
     , ('int occaecat cupidata', 'ollit anim id es', 't non proident, sunt in culpa ')
     , ('pariatur. Ex', 'ex ea co', 'pa qui officia deserunt')
     , (' aliquip ex ea commodo cons', 'rehenderit in v', 'um dolore ')
     , ('qua. Ut eni', 'x ea commodo', 'e veli')
     , ('nim veniam, quis nostrud e', 'piscing elit', 'Excepteur sint occaecat c')
     , ('itation ullamco laboris nisi u', ' cupidata', 'ercitation u')
     , ('im veniam, quis nostrud exerc', 't dolore magna', 'ia deserunt mollit anim id e')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('r. Excepteur sint occ', ' in culpa qui ', ' commodo consequat. Duis aute ')
     , ('r incididunt ut labore', 'cte', 'um.Lorem ipsum dolor sit amet')
     , ('cing elit, sed do eiusmod', 'd exercitation u', 't labore et dolore magn')
     , ('do eiusmod tempor inc', 'lor i', ' adipiscing elit, sed do')
     , ('n reprehenderit in volupta', 'eur sint o', 'o consequat. Duis a')
     , ('o laboris nis', 'ad min', ' in culp')
     , ('ncididunt ut l', 'or s', 'unt ut labore et')
     , ('or incididunt ut labore et dol', ' dolore ', ' labore et dolore magn')
     , ('ur adipiscing elit, sed do', 'm a', 'uptate velit esse cillum do')
     , (' reprehenderit in voluptate ve', ' et dolore magn', 'ui officia deserunt mollit ')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('piscing', 'ure d', 'lit esse')
     , ('lit esse ci', 'p ex', 'ris nisi ut aliquip ex e')
     , ('di', ' fugiat ', 'quat. Duis aute ')
     , ('unt in culpa qui officia de', 'aborum', 'aute irure dolor in')
     , ('enim a', 'cididunt ut lab', ' dolore eu fugiat nulla pari')
     , ('luptate ve', 'a pariatur. Ex', 'luptate velit esse cillum')
     , ('qua. Ut enim ad minim venia', 'at nu', 'upidatat non proide')
     , ('aboris nisi u', 'pa ', 'or')
     , ('sit amet, consectetur adipis', 'velit esse ci', 'Excepteur si')
     , ('re et dolore magn', ' U', 'ua. Ut en')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' o', 'rehenderit in ', 'x ea commodo consequat. Du')
     , ('lpa qui officia deserunt molli', ', s', 'onsequat. Du')
     , ('ariatur. ', 't, sunt in ', ' enim ad minim veni')
     , ('luptate', 'pteur si', 'u')
     , ('t occaecat cupidatat ', 'id est la', 'iatur. Excep')
     , ('irure dolor in reprehen', 'inim v', ' ullamco')
     , ('ute irure dolor in re', 'r sit am', 'giat nulla pariatur. Excepteur')
     , ('gna a', 'pa', 'velit esse cill')
     , ('citation u', 'nostru', ' nostrud exercitation ul')
     , ('t cupidatat non proident, ', 'llit ani', 't laborum.Lorem ipsum dolor')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' con', 're eu f', 'in reprehenderit i')
     , ('r. Excepteur s', 'ci', 'd exercita')
     , (' amet, consectetu', 'cupidatat', 'co laboris nisi ut')
     , ('atat ', 'elit ', 't ani')
     , ('aecat cupidatat', 'unt molli', 'icia deserunt mo')
     , ('na aliqua. Ut enim ad m', 'etur adipis', 'est laborum.Lorem ipsum d')
     , ('itation ul', 'am,', 'didunt ut ')
     , ('niam, quis nostrud ', 'piscing elit,', 'ore ma')
     , ('nim i', 'do consequat. ', 'a.')
     , ('ea commodo consequat. Du', 'ur. Ex', 'olor in re')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('ull', 'ol', 'consequat. Duis au')
     , (' labore et do', 'n ullamco labor', 'r incididunt ut labore et do')
     , ('lla pariatur. Exc', 'sse', 'nt ut labore et dolore ma')
     , (' fugiat nulla ', 'um dolor si', 'lit, sed do eiusmod ')
     , ('datat non proident, sun', 'dolor in ', 'rehend')
     , ('eniam, quis nostrud exer', 'la', 'voluptate vel')
     , ('lli', 'd tempor inc', 'lor sit amet, consectetur adip')
     , ('officia deserunt molli', 'anim id est lab', ' dolor in repre')
     , ('rure dolor in reprehend', 'psum do', 'nderit in volupt')
     , ('ad minim ve', 'ci', 'g elit, sed do')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('elit, sed d', 'p ex ea ', 'serunt mollit anim id est la')
     , ('minim veniam, q', 'mag', 'eserunt mollit an')
     , (' ea commodo cons', 'rehenderit in v', 'ectetur adipiscing elit')
     , ('nulla pariatur. Exce', 'in volup', 'lla pariatur. Excep')
     , ('est laborum.Lorem ipsum dolo', 'e et', ' quis n')
     , ('re dolor in reprehende', 'u', 't ut labore et dolore mag')
     , ('p', 't laborum.', 'qua. Ut')
     , ('sit amet, co', 'd e', 'ore magna aliqua. Ut enim a')
     , ('eur sint occaeca', 'd do eiusmod t', 'oc')
     , ('lamco laboris nisi ut ', ' anim id est ', 't aliquip ex e')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('e irure dolor in re', 'icia dese', 'labo')
     , ('smod tempor inci', 'm veniam', 'd te')
     , ('enim ad ', 'henderit in vo', 'ficia')
     , ('t. Dui', 'ug', ' ex ea commodo co')
     , ('aliqua. Ut enim ad minim', 'int occaeca', 'bore et dolore magna al')
     , ('irure', ' qui officia ', 't aliquip ex ea c')
     , ('ptate velit esse cillum dolore', '. Excepteu', ' nulla pari')
     , ('lum ', 'laborum.Lore', 'cia deserunt mollit')
     , ('uip ex e', ' fug', 'd est laborum.Lorem ipsum dol')
     , ('lore magna aliqua. Ut', 'scing elit, s', '. Ut enim ad minim ve')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('a deserunt mollit anim id e', 'lor in rep', 'lum dolore eu fugiat nul')
     , ('lit esse cillum dolore e', 'roiden', 'abore et ')
     , ('ud exercitation', 'ullamc', 'magna aliqua. Ut enim ad mi')
     , ('ed do eiusmod t', 'e cil', ' eiusmod tempor incididunt ut ')
     , ('id est laborum.Lorem ip', 'ommo', 'x ea commodo con')
     , ('s nisi ut aliquip ex ea c', 'exerc', 'm, qu')
     , ('amco lab', 'Excepteur sint', 'nim ')
     , ('unt in c', ', sunt in c', ', quis nostrud e')
     , ('t esse cillum dolore ', 't, sed', 'ullamc')
     , ('t. Duis aute irure dol', 'cepteur sint occ', 'commodo con')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('unt ut labore et dolore magna', 'st labor', 'erunt mollit anim id est la')
     , ('uis ', 'aliquip ex ea c', 'm, qu')
     , ('cillum dolore eu ', 'epteur s', 'orum.Lorem ip')
     , ('i ut aliquip ex ea commodo co', 'iru', ' sed do eiu')
     , (' enim ad minim venia', '. Ut enim ad mi', 'giat nulla pariatur. ')
     , ('in reprehenderit i', 'roident, sunt ', 'it amet, consectetur a')
     , ('laboris nisi u', 'por incidid', 'unt in culpa qui offic')
     , ('amco labo', 'erit i', 'icia deserunt mollit anim id')
     , ('lamco laboris nisi u', 'o', 'it, sed do eiusmod te')
     , ('aliquip ex ea comm', 'ipsum d', 'm.Lorem ipsum dolor sit am')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('aecat cu', 'proide', 'unt in culpa qui officia d')
     , ('xcepteur sint', 'uis aute iru', 'm dolor sit amet, consectetu')
     , ('xercitation ullamco labo', 'r ', 'ectetur adipisc')
     , ('mollit a', 'mod tempor in', ', sunt in culpa qui')
     , ('ugiat nu', 't occaecat c', 'sed do ')
     , ('nt occaecat cupidatat non', 'tat non proiden', ' commodo consequ')
     , ('um', 'ons', 'co laboris nisi ut ')
     , (' volu', 'pisci', 'citation ullamco l')
     , ('olore eu fugiat nulla pariatur', ' ', 'm dolore eu fugiat null')
     , ('ollit anim id est l', 'dolo', ' reprehe')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' exercitation ullamc', 'm id es', ' reprehenderit in volupta')
     , ('nt in culpa ', ' dolor', 'od tempor incididunt ')
     , ('culpa qui officia deserunt', ' co', 'quip ex ea com')
     , ('d te', ' esse c', 'um dolor sit amet, co')
     , ('illum d', 'in', 'deserunt m')
     , (' reprehend', 'ta', 'quip ')
     , ('t anim id est lab', 'fficia deserunt', 'prehenderit in volupta')
     , ('nt occaecat cupidatat non p', '. Dui', 'nostrud')
     , ('e cillum ', 'ipiscing eli', 'isi ut aliquip ex ea com')
     , (' est lab', 'um dolor sit ', 'est laborum.Lorem ipsum dol')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('r adipiscing elit, sed do ', 't ', 'tetur adipiscin')
     , (' est', 'cidid', 'nostr')
     , ('iam,', 'ri', ' consect')
     , ('t al', ' esse ci', 'do ei')
     , ('mpor incididunt ut labore ', ' ut labore et do', 'l')
     , ('d', 'ui officia deser', 'a. Ut enim ad min')
     , ('i officia deserunt mol', 'met, conse', 'piscing elit, sed do eiusmod')
     , ('pidatat non proident, sunt in', 'na ', ' veniam, quis nostru')
     , ('met, consectetur adip', 'ercitation ul', 'oluptate vel')
     , ('o eiusmod tempor', ' aliquip ', 'occaecat cupidatat non pr')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('odo consequat. Duis aute', ' dolor ', ' pariatur. Excepteur ')
     , ('dolore magna aliq', 'nisi ut aliqu', 'dipisc')
     , ('r. Except', 'n u', ' nisi ut aliquip ex ea c')
     , ('isi ut aliquip ex ea commodo c', ' Excep', 'ehenderit in voluptat')
     , ('t cupidatat non proid', ' eu fugiat nul', 'luptate vel')
     , ('rit ', 'cat cupi', 'rcitation ullam')
     , (' et dolore magna ali', 'eru', 'teur sint occaecat cupidata')
     , (' ut labore et dolore magna al', 'pteur s', 't ut labore e')
     , ('t', 'r adipis', 'd tempor i')
     , ('eiusmod ', 't enim ', 'int oc')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('minim veniam', 'iat nul', 'im ad minim veniam, qu')
     , ('ercitation ullamco laboris n', 'u', 'elit, sed do eiusmod tempor in')
     , ('olore eu', 'v', 'bore et dolore magna aliq')
     , ('iscing e', 'modo consequa', 'lamco ')
     , ('int occaecat c', ' ut aliquip e', 'por incididunt ut labore et ')
     , (' sed do eiusmod tempor incidi', 't cupidat', 'ut ali')
     , ('uptate vel', 'on ', ' co')
     , ('liquip ex ea commodo consequ', 'ex ea commo', ' aliquip ex ea ')
     , ('.L', 'is nostrud exerc', 'derit in')
     , (' sunt in culpa qui off', ' qui', 'sequat. Duis aute ir')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('it, sed do eiusmod tempor', 'voluptate velit', 'Excepteur ')
     , ('e ', 'lor in re', 'uat. Duis a')
     , ('d minim veniam, q', 'ng elit,', 'oluptate veli')
     , ('cepteur sint o', ' adipiscin', 'ua. Ut enim')
     , (' exercit', ' minim veniam, q', 'o l')
     , ('lla pariatur.', 'quip e', 't. Duis aute irure dol')
     , ('idunt ut la', 'ficia deserun', ' pariatur')
     , ('nt mollit anim id es', 'iusmod te', 'fficia deserunt')
     , ('rud exercitatio', 'r incididunt', ', ')
     , ('n voluptate velit esse cillu', 'la pariatur. Ex', 'uis n')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('it, se', ' nostrud exer', 'olor in reprehender')
     , ('tur adip', 'ea commodo c', 'riatur. Excepteur sint ')
     , ('eprehenderi', 'a', 'xcepteu')
     , ('s no', ' in ', 'amco l')
     , ('pt', ' sit amet, c', 't esse cillum dolore eu fugiat')
     , ('riatur. Excepteur', ' id est l', 'r sint oc')
     , ('rure dolor in reprehenderi', 'ore magn', 'iqui')
     , ('r incididunt ut labore ', 'ariatur. Except', 'labo')
     , (' dolor sit amet, ', 'aute iru', ' laboris nisi ut aliquip ')
     , ('minim veniam, quis no', 'odo cons', 'laboris n')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('o consequat. Duis aut', 'o eius', ' ad minim ve')
     , ('x ea commodo consequat. Dui', 'qua. Ut', 'sed do eiusmod tempor')
     , ('llamco laboris nisi ut ali', 'dolore mag', ' minim ven')
     , ('boris nisi ut aliquip ex', 't enim a', 'ulla pariat')
     , ('aliqua. Ut en', 'qu', 'ullamco laboris nisi ut a')
     , ('r in reprehen', 'uat', 'iam, quis nostrud exerc')
     , ('t, sunt in culpa qui officia', 'mmodo consequat.', 'eserunt moll')
     , ('xercitation', 'cita', 'voluptate velit esse c')
     , ('lla pariatur. Excepte', ' adipiscing ', ' occaecat cupidatat')
     , ('rit in voluptate ve', ' re', 't, sed do eiusmod tempo')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('erunt mollit a', 'ullamc', 'modo consequat. Duis a')
     , ('or sit a', 't non proiden', 'veniam, quis nostrud exercita')
     , ('ia deserunt mo', 'laboris ', 'lit anim i')
     , ('tio', 'consequ', 'teur sint occaecat cup')
     , ('sed do eiusmod te', 'iatur. ', 'a qui officia deserunt m')
     , ('laborum.Lorem ips', 'em ipsum do', 'erunt ')
     , ('ure dolor in reprehenderit in', 'por inci', 't')
     , ('ur', 'or incididunt u', ' ')
     , (' in ', ', sunt in cul', ' la')
     , ('rure dolor in reprehenderi', 'ae', 'pa qui officia deseru')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('s nostrud exercitatio', 'riat', ' nulla p')
     , ('ru', ' ni', 'id')
     , ('nostrud exercitat', ' deserunt', 'elit esse cillum')
     , ('tur adipiscing elit, sed do ei', 's', ' nulla pariatur. Exc')
     , ('o', ' ', 'r sit')
     , ('im ad minim veniam, quis nos', 'Lorem ip', 'lamco laboris nisi')
     , ('Ut enim ad m', 'onsectetur adip', 're et dolor')
     , (' ', ', con', 'cing elit, ')
     , ('idatat non proid', 'laboris nisi ut ', 'd es')
     , ('or incididunt ut la', 'anim ', ' velit esse cillum dolore eu f')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('a commodo consequat', 'is', 'luptate velit')
     , ('t ut ', ' id es', 'nseq')
     , ('ate velit ', 'Except', 'qu')
     , ('uptate velit esse cillum dol', 'ris nisi ut ', 're dolor')
     , ('m dolor sit amet, co', 'am', 't a')
     , ('riatur. Excepteur sint o', ' eiusm', 'pariatur. Ex')
     , ('tetur adipiscing ', 'ulpa qui o', 'isi ut aliquip ex ea commodo c')
     , ('a. Ut enim ad mini', ' in vol', 'velit es')
     , ('tur. Excepteur sint occaec', 't laborum', ' dolor ')
     , ('tation ullamco laboris ni', 'liqua. Ut', 'inim veniam, q')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' ut labore et dolore magna al', 'e et dolo', 'd exercitation ullamco labo')
     , (' dolor sit amet, ', 'lla pariatur. E', 'citation ullamco laboris')
     , ('itation ullamco laboris nisi ', 'boris nisi ', 'r sint occaecat cupidatat n')
     , ('mpor incididunt ut l', 'cat cupidatat', 'tur. Excepteur s')
     , ('ur. Excepteur sint occaecat ', 'te irur', 'tate velit esse ci')
     , (' anim id', 'im id e', 'es')
     , ('la pariatur. Exc', 'in r', 'roident')
     , ('liquip ex ea commodo ', 'cat', 'borum.Lorem ipsum dolor si')
     , ('citation u', 'ore et', 'nim ad minim veniam, quis ')
     , ('riatur. Excepteur sint oc', 'or in r', 'ostrud exercitati')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' velit esse cillum ', 'eprehen', 'boris nisi ut a')
     , ('non', 'lpa qui o', 'co laboris nisi ut')
     , ('co', ' sin', 'p ex ea ')
     , ('rehenderit in vol', 'ididu', 'd minim veniam, quis nostr')
     , ('m ', 'sunt in culpa qu', 't non proident, sunt in c')
     , ('ata', '. U', 'it amet, cons')
     , ('r. Excepte', 'epteur s', 'lla pariatur. Excepteur sint ')
     , ('t laborum.Lorem ip', 'um dolor sit ', 'culpa')
     , ('minim ve', ' aliquip ex', 'it in voluptate velit ess')
     , ('voluptate velit esse cil', 'e magna aliqua. ', 'ur sint occaecat cu')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('et, consecte', 'eli', ' culpa qui officia d')
     , ('cididunt ut labore et ', ' volu', 're eu f')
     , (' amet, consectetur adipiscing ', 'r i', 's aute irure dol')
     , ('im veniam, quis nostrud', 'in repr', 'sequat. Duis aute ')
     , ('sit amet, consectetur a', 'u', 'odo consequat. Duis aute iru')
     , ('ulla pariatur. Excepte', 'tur. Excepteur s', 'cia deserunt mollit')
     , ('irur', 'm id est laboru', 'minim veniam,')
     , (' eu fugiat null', 'in culp', 'm ad minim veniam, quis no')
     , ('Duis aute irure dolor in repre', 'it, sed do ', 'onsequat. Duis aute irure ')
     , ('t ut labore et dolore magna', 'r sit am', 'velit esse cillum dolore')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('quat. Duis au', 'im veniam, quis ', 'co laboris nisi ut ')
     , (' eiusmod tempor inc', 'Excepteur sint ', 'r sit amet, consectetu')
     , ('dolor si', ' ', 'n ullamco laboris nis')
     , (' ut labo', 'lor sit', 'sed do eiusmod te')
     , (' adipiscing elit, sed do', 'r incidi', ' qui')
     , ('a pariatur. Excepteur sint o', 'odo ', 'm')
     , ('fugiat nulla pariatur. Ex', 'a par', ' eu fugiat null')
     , ('boris nisi', 't labore ', 't esse ci')
     , ('or incididunt ut', 'm, q', 'volu')
     , ('t, sed do eius', 'm,', ' irure ')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('inim ve', '. Excepteur sin', 's nisi ut aliquip ex ea commod')
     , ('nim ', 'lit, sed do ei', 'pteur sint occaecat cup')
     , ('mod tempor inci', 'rcitation ull', 'qu')
     , ('sun', 'a. Ut enim ', 'd minim ')
     , ('si ut aliquip ex ea commodo co', ' ', 'it')
     , ('d est laborum.Lor', 'labori', 'qui officia deserunt mo')
     , ('sunt in culpa', 'rem', 'isi ut aliquip ex ea')
     , ('est', 'pt', ' nulla paria')
     , ('adipiscing elit, sed do eiu', 'erunt mollit ', 's aute irure dolor ')
     , ('sit amet, consecte', 't esse cillum', 'anim id est laborum.Lore')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('D', ' proident,', 'atat non proident, sunt ')
     , ('reprehenderit in volupta', 'ad minim v', 't cupidatat non p')
     , ('d exercitation ullamco labo', 'uat. D', 'trud exercit')
     , ('fugiat null', 'inim v', 'is nostrud exercitation ullamc')
     , ('sin', 'quat. Duis aute ', 'quat. Duis aute irure ')
     , ('ea commodo consequat. Duis ', ' aute irur', 'e magna a')
     , (' amet, consectetur adipi', 'ident, sunt in', 'e velit esse cillum ')
     , ('tation ullamco laboris', 'tat n', 'ut aliquip e')
     , ('re magna aliqua. Ut e', 'ullamco', 'dolor in reprehe')
     , ('modo', 'Ut enim ad m', ' Ut enim ad mini')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('em ipsum dolor sit amet, co', 'er', 'a deserunt mollit anim')
     , ('dent, sunt in culp', 'ad m', 'atat non proident, sunt')
     , ('dent, sunt in cul', 'x e', 'a')
     , ('aliqua. Ut enim ad minim venia', 'ate veli', 'consecte')
     , (', quis nostrud exercitation', 'or in repreh', '. Duis aute irure do')
     , ('se cillum dolore eu fugiat nu', 'ore eu fugiat ', 'quis nostrud exercitation u')
     , ('mod tempor incididunt ut ', 'aboris nis', ' anim id es')
     , ('non ', 'ull', 'labo')
     , ('eiusmod tempor incidi', ' ', ' elit, sed do eiusmod tempo')
     , (' dolor in rep', 'it, sed', ' amet, consect')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('lum dolore', 'ex ea comm', 'rud ')
     , ('ercitation ullamco laboris n', 'm ve', 'ip ex ea commodo consequat. D')
     , ('trud e', 'm ad ', ' ut aliquip ex ea commodo con')
     , ('tur.', ' exercitation', 'te vel')
     , ('nt in culpa qui officia deseru', ' est laborum', 'qua. Ut enim ad mini')
     , ('nt ', 'eur ', 'pidatat non proiden')
     , ('m', 'pi', 'ur sint occ')
     , ('st laborum.L', 'a commo', 'roident, sun')
     , ('trud exercitation ullamco l', 'data', 'commodo consequat.')
     , ('ut', 'm id est labo', ' pariatur. Excepteur')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('nt mollit anim', 'tat', 'int occaecat cupidatat non')
     , (' Excepteur sint o', ', sunt in c', ' occaecat cupidatat no')
     , ('laboris', ' dolore magna a', 're')
     , ('ctetur adipiscing elit, sed', 'im ad ', 'te irure do')
     , ('nostrud e', 'n culpa qu', 'epteur sint occaecat c')
     , ('pidata', 't occaecat cup', 'd est ')
     , (' ullamco lab', 'commodo conseq', ' deserunt')
     , ('d', 'niam, quis nos', 'citation ullamco labo')
     , ('t anim id e', 'lore eu fugiat', 'llamco la')
     , ('ud exercit', ' cillum ', 'Dui')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('m dolor', 'or in reprehend', 'iusmo')
     , ('do ', 'uip', 'labore et dolore ')
     , ('ua. Ut', 'upidata', 'labore et dolore mag')
     , ('i', ' deserunt ', 'e magna aliqua. Ut en')
     , ('cing elit, sed ', 'p', 'tation ullamco labori')
     , ('dent, sunt in culpa qui off', 'quat. Duis aute ', 'nsequat. Duis')
     , ('a. Ut enim ad minim veniam,', 't, su', 'sunt in culpa qui off')
     , ('esse cillum dolore eu fu', 'u ', 'm')
     , ('quip ex ', ' commodo cons', 'quat. Duis aute ')
     , ('m dolore eu fugiat nulla pa', ' qui officia d', 'ate velit esse cillum')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('p ex ea commodo conse', 'm.Lo', 'e et dolore magn')
     , ('p', 'cing ', 'mpor incididunt ut labor')
     , ('t ut', ' f', ' dolore ')
     , ('quat. Duis aut', ' id es', 'on proident,')
     , (' ea commo', 'oll', 'abore et dolore magna ali')
     , ('im id est laboru', 'nt ', 'ser')
     , ('cididunt ut labore et do', 't', 'ugiat nul')
     , ('oris nisi u', 'nim ad minim ', 'ipsum dolor sit amet, co')
     , ('amco l', 'cia deserunt ', 'im veniam, quis n')
     , ('in culpa qui officia deserunt ', 'citation ull', 'r sit am')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('ctetur adipiscin', ' non proid', 'cing elit, sed do eiusmod tem')
     , (' fugiat nulla pariatur', 'niam, quis ', 'quis nostrud exercitation u')
     , ('caecat cupidatat', 'laborum.Lorem', 'or in reprehen')
     , ('it amet', 'rud ex', 'enderit in voluptate velit e')
     , ('tate velit ', 'g elit, sed', 'nim id est labor')
     , ('p ex ea c', 'st labor', 'equat. Duis aute irure d')
     , ('henderit in v', 'ariatur. Exc', 'quip ex ea commodo consequat. ')
     , (' labor', 'niam, quis', 'enim ad minim veniam,')
     , ('uat. Du', 'ncididunt', 't occaecat cupidatat non pr')
     , ('t in voluptate v', ' nostru', ' culpa qui officia deseru')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('en', ' ', 'magna aliqua. Ut enim ad')
     , (' in reprehenderit in volupt', 'in', 's nisi ut aliquip ex ea com')
     , (', sed do eiusm', 'anim id est la', 'ident, sunt ')
     , (' irure do', ' Duis aute irur', 'st laborum.Lorem ipsum do')
     , ('magna ali', 'usmod tempor inc', 'consequat. Duis aut')
     , (' fugiat nulla pariatur', 'is n', 'd do eiusmod tem')
     , ('ut aliqu', 't mollit an', 'od temp')
     , ('isi ut aliqui', ' Duis aute irur', 'd tempor incidi')
     , ('enderit in voluptate velit ess', 'boris', 'dent, sunt in culp')
     , (' aliqua. Ut enim ', ' aute iru', 't anim id est laborum.Lor')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' in volupta', 'pa qu', ' adipiscing elit, sed ')
     , ('eniam, quis no', '. Du', 'nt, sun')
     , (' minim veniam, ', 'se cillu', 'te velit esse ci')
     , ('boris nisi ut aliquip ', 'em', 'rem ')
     , ('mod tempor incididunt ut labor', 'm dolore e', 'olore magna aliqua. U')
     , ('occaecat cupidatat', 'e dolor in repr', 'o labor')
     , (' qu', ' iru', 'm veniam, quis nostrud ex')
     , ('n proident, ', ' reprehenderit ', 'strud exercitation ullamco lab')
     , (' ', 'e et dol', ' la')
     , (' incididunt ut labore et do', 'ad', 'r. Excepteur sint occae')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('abo', 't laborum.Lore', 'ris nisi ut aliq')
     , ('nt, sunt in', ' in reprehenderi', 'ugiat nulla pari')
     , ('t in voluptate velit esse ', 'ng elit, s', ' reprehende')
     , (' in volupta', 'x ea commodo co', ' magna aliqua. Ut')
     , ('um dolor sit amet, co', 'unt mollit an', ', consectetur adi')
     , ('lit esse ', 'aborum', 's a')
     , ('nt occaecat cupidatat non pr', ' ad', 'id')
     , (' dolor ', 'uis aute i', 'dolore magna aliqua. Ut enim')
     , (' quis nostrud exercitation ', 't', 'olupta')
     , ('olore eu fugiat null', 'm veniam, qu', ' magna ')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('fficia deserunt mollit', ' elit, sed do e', ' dolore')
     , ('ommodo consequat. Duis a', ' ipsum dolor sit', ' proident, sunt in ')
     , (' magna aliqua. Ut enim ad ', ', sed do eiu', ' ad minim veniam,')
     , ('borum.Lorem ip', ' ', ' tempor incididunt ut labore e')
     , ('t occaecat c', 'qua. Ut enim ad', 'at nulla pari')
     , ('ctetur adipisci', 'sse c', 'pidatat n')
     , (' sed do eiusmod te', ' ', 'sse ')
     , ('in reprehenderit in voluptat', ' paria', 'ipsum dolo')
     , ('ident, sunt in ', 'ore eu fugiat nu', 'ariatur. Excepteur sint o')
     , ('lit, sed do eiusmod', 'r sit a', 'lpa ')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('equat. Duis a', 'magna a', 't amet, consectetur')
     , (' ', 'nost', 'ed')
     , ('nulla pariatur. Excepteur si', 'eru', ' veniam, quis nostrud exercit')
     , ('r adipiscing elit, se', 'nim veniam, ', 'im ad minim ')
     , (' dolo', ' magna aliqua. U', 'henderit in voluptate veli')
     , ('ng elit, sed do eius', 'ation ullamco ', 'or sit amet, consec')
     , ('m a', 'veni', 'dolore magna ')
     , ('r adipiscing elit, sed', 'u', 'm dolor si')
     , ('dolore eu fugiat nulla par', 'tempor inci', 'a')
     , ('do c', 'ident,', 'ollit anim')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('commodo con', 'te iru', 'liqua. Ut enim ad minim ve')
     , ('d', ' nulla p', 't occaec')
     , ('do eiusmod tempor', 'laborum.', 'ng elit, sed do eiusmod ')
     , ('lor in repre', 'lor', 'veniam, quis nostru')
     , ('met,', 'mco la', 't,')
     , ('id est laborum.Lorem ipsum', 'par', 't am')
     , (' Duis aute irur', 'adipisci', 'eniam, qui')
     , ('consectetur adipisc', ' aute irure', 'nisi ut aliquip e')
     , (' esse cillum dolor', 'datat non proid', 'amet, consectetur adip')
     , ('labore ', 'r. Excep', 'lamco laboris nisi ut a')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('it amet,', 'ur', 'do eiusmod tempor incidid')
     , ('nim veniam, quis nostrud ', 'derit in v', 'ctetur adipiscing elit, s')
     , ('riatur. Excep', ' enim ad ', 'rehenderit in v')
     , ('derit in voluptate ve', 'cae', 't')
     , ('idatat non proident, sunt i', 'pidatat', 'oluptate velit esse cillum dol')
     , ('eprehenderit', 'n', 'm ipsum dolor ')
     , ('m dolor', 'ion ullam', 'it, sed do ')
     , ('. Duis aute', 't, c', '.Lorem ipsum dolo')
     , ('ris nis', 'pa qui off', 'si ut aliquip ex ea comm')
     , ('cia deserunt mollit anim id e', 'adipiscing', 'is aute irure do')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('na aliqua. Ut enim a', 'gna aliqua. U', ' ')
     , ('e', 'pidatat non ', 'uis nost')
     , ('r sit amet, conse', ' inc', 're et dolore magna aliqua. Ut')
     , ('odo consequat. Duis ', 'ud exercita', 'ident, sunt in culpa q')
     , (' ut', 'at. Duis au', 'a p')
     , ('e dolor in repreh', 'c', 't en')
     , (' in culpa ', 'ehenderit ', 'uptate velit esse ci')
     , ('enim ad minim venia', 'u fugia', 'amet, conse')
     , ('icia deserunt molli', 's aute ir', 'occa')
     , ('unt mollit ani', 'atur. ', 'qui of')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('mpor incid', 'am', 'o')
     , ('n proide', 'r', 'lore magna a')
     , ('r', 'lpa qui offi', 'elit, s')
     , (' do', 'exercitation u', 'la ')
     , ('aliqua. Ut eni', 'nt, sunt in c', 'amet, consectetur')
     , ('ea commodo con', ' dolore magna', 'unt molli')
     , ('erit in vo', 'erunt moll', 'ulla pariatu')
     , ('at nulla pariatur. Ex', 'iatur. ', 's ')
     , ('ulpa qui officia des', 'su', 'icia deserunt mollit anim id ')
     , ('iat nulla p', 'dent, sunt ', 't non pr')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('it amet, consectetur adipisc', ', s', 'unt ut labore et dolore magna ')
     , ('ed do eiusmod tempor incididu', 'rem i', 'Ex')
     , (' minim ven', 's nostrud ex', 'x ea ')
     , ('pteur sint occaecat cupid', 'olore m', 'se cillum dolore ')
     , ('r', 'dipiscing', 'l')
     , ('m', 't, con', 'ad minim veniam,')
     , ('o l', 't amet, c', 'qui')
     , ('na aliqua. Ut en', 'trud exercit', 'e irure dolor in re')
     , ('boris nisi ut aliquip ex ea co', 'r. Excepteur ', 'co laboris nisi ut aliqu')
     , ('in voluptate velit esse cillum', ' repre', 'dese')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('ugiat nulla paria', 'temp', 'epteur si')
     , ('enderit in voluptate ', 'Exc', ' irure dol')
     , ('caecat ', 'quis nostrud ex', ' occ')
     , ('im ad minim veniam, quis nos', ' nisi ut ', 'ing elit, sed do eius')
     , ('qua. Ut e', 'ris nisi ut a', '.Lorem ipsum dol')
     , ('aecat cupidatat non proi', 'ui offic', 'tur. Excepteur sint occae')
     , ('equat. ', 'ad minim ', ' veli')
     , ('officia deserunt mollit anim ', 'upidatat non', ' qui officia deserunt mollit a')
     , ('xcepte', 'g elit, sed do ', 'sed do eiusmod tempor inci')
     , ('ing el', 'in culpa ', 'tempor incididunt u')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('rehen', 'fu', ' et dolore m')
     , ('r incididunt ut labo', 'nderit in', 'cididunt ut labore et d')
     , ('uptate velit esse cillum do', 'ed do eiu', 'olor sit amet, consectetur')
     , ('laborum.Lorem ipsum', 're et dolore ma', 'qua. Ut enim ad minim v')
     , ('pteur', ' tempor incidid', 'od t')
     , ('is', 'm.Lorem ip', 'ut aliquip ex ea ')
     , ('strud exercit', 't amet, consec', 'ate velit esse cillum ')
     , (' et dolore magna a', 'nsequat. Dui', ' in vol')
     , (' fugiat nulla pariatur. Exce', 'eprehen', 'llamco laboris n')
     , ('ent, s', 't an', 'eu fugiat nulla pari')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('t ', 'trud exercitatio', 'mmodo consequa')
     , ('i', 'laborum.Lorem', 'on proident, sunt')
     , ('ia deserunt mollit anim id es', ' velit ', 'nim id est laborum.Lorem i')
     , ('olore eu fugiat nulla pariatu', ' minim veniam, ', 'tur adipiscin')
     , ('olor sit amet, consectetu', 'ure d', 'quis nostrud exercita')
     , (' exercitation ulla', ' volup', ' adipiscing eli')
     , ('quat. Duis aute ', 'm ad min', 'cupidatat non proident')
     , ('rure dolor in reprehender', 'ipsum do', 'im id est laborum.Lorem ip')
     , ('riatur. Excep', 'strud exe', 'l')
     , ('r. Excepteur sint ', ', sunt in culpa', 'liqua. Ut enim ad')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' tempor incididunt ut lab', 'm, qui', ', co')
     , ('. Duis aute irure dolor i', ' dolor sit a', 'tate velit esse cill')
     , ('sum dolor sit amet, consecte', 'd ', 'anim id est labor')
     , ('ate velit esse cillum dol', 's', 'id')
     , ('e velit esse cil', 'at cupidata', 'isi ut aliquip ex ea commo')
     , ('rehenderit in voluptate vel', 's ', ' E')
     , ('xercitat', 'reprehen', 'scing ')
     , ('onsequat. Duis aute irure d', 'olor', 'm veniam, quis nostrud exercit')
     , (' dolor', 'up', 'n proident, sunt ')
     , ('in culpa qui offi', ' r', 'iquip ex ea ')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' dolore magna aliqua. Ut enim', ' culpa qui o', 'ur adipiscing elit, sed d')
     , ('d', 'od tempor ', ' dolore m')
     , (' minim', ' labore et dolo', 'uis nostr')
     , ('deserunt mollit anim id', 'iam, quis nostru', ' et dolore')
     , (' ', 'usmod tempor ', ', ')
     , ('onsectetur adi', 'im veniam', 'erit in')
     , ('cillum dolo', 'i', 'atat non proident, sunt in ')
     , (' velit esse cillum dolore eu f', ' veniam, qui', 'ficia dese')
     , ('aute ', 'caecat cup', ' deserunt mol')
     , (' consectetur adi', 'proident, sunt', 'eiusmod tempor inc')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('is nisi ut aliquip ex ea com', 'n', 't dolore magna aliqua. Ut en')
     , (' tempor incididunt ut lab', 'ut a', 'ullamc')
     , ('modo consequat. ', 'ru', 'ommodo consequat. Duis aute')
     , ('t', 'iusmod tempor in', 'it anim id')
     , ('iquip ex ea commodo cons', 'um dolor sit a', 'in voluptate ')
     , ('citation ullamco laboris ni', ' Ut enim', 'ut labor')
     , ('iqu', 'ia ', 'lum dolore eu fugiat ')
     , ('is nostrud exerc', 'co labori', 'uis n')
     , (' dolore eu fugia', ' exer', ' consectetur ad')
     , ('it in voluptate v', 'caecat cup', 'teur sint occaecat')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('voluptate velit esse ci', 'niam, quis no', ' amet, consectetur ad')
     , (' in v', 's nisi ut aliqui', 'm, qu')
     , (' pariatu', 'im ad minim ven', ' nostrud exer')
     , ('didun', 'ore eu fugiat ', 'borum.Lorem ips')
     , (' reprehender', 're e', 'roident,')
     , (' dolore magna aliqu', 'ficia deseru', 'ud')
     , ('inim veniam, qu', ' cil', 'nsequ')
     , ('d exercitati', 'n ullamco labo', 'i')
     , ('sunt in culpa qui offi', 'rehenderit', 'n proident, sunt in cu')
     , ('ing elit, sed do eiusmo', 't non proident, ', 'or incididunt ut labore e')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('e velit esse cillum dolo', 'e vel', 'aboris ')
     , (' qui officia des', 'e magna al', 'xcepteur sin')
     , (' ipsum dolor sit ame', 'mpor in', 'nim veniam, quis no')
     , ('ccae', 'te irure ', 'or sit amet,')
     , ('or in rep', 's', 'ptate velit es')
     , ('m', 'qua. Ut en', 'im ad minim veniam, quis nostr')
     , (' ex', 'ctetur adipisci', 'ariatur. Excepteur sint o')
     , ('lpa qui officia deser', 'iscing elit, s', 'p')
     , ('se cillum dolor', 'e', 'idunt ut labore et ')
     , ('llam', 'unt ut labo', 't aliquip ex ea comm')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('est laborum.L', 'ididunt ut labor', 'onsequat. Du')
     , ('olor sit amet, ', 'oris nisi ut ', ' in reprehenderit ')
     , ('m ', 'lit anim id', 'pteur sint occaecat cupida')
     , ('aecat cupidatat non proident', 'is nostrud ex', 'liqua. Ut enim')
     , (' eiusmod tempor inci', 'a', 'ident, s')
     , (' sed do eiusmod tempor', 'cat cupidat', 'a d')
     , ('dipiscing elit, sed do', 'rure dolor in r', ' nulla pariatur')
     , (' laboris nisi ut ali', 'veni', 'n proident, sunt in culpa')
     , (' dolor in reprehenderit in', ' est labor', 'o ')
     , (' non proide', ' do', 'r sint occaecat')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('g elit, sed ', 'atur', 'ris nisi ut aliquip ex ea co')
     , ('d exercitation ul', ' exercitation ul', 'aec')
     , ('a deserunt mollit', 'fugiat nulla ', 'upidatat no')
     , ('consectetur adipi', ' ullam', 'ad minim ')
     , ('di', 'ariat', 'm, quis nostrud ')
     , ('a pariatur. Excepteur sint oc', 'sequat. Duis', 'co laboris nisi ut ')
     , ('ccaecat cupidatat non proi', 'm id est', 'ing el')
     , ('ur. Excep', 'nt', 'in culpa qui officia deserunt')
     , ('ulla pariatur. Excepte', 'ore', 'tat')
     , ('r sit amet, consectetur adipis', ', sunt', 'inim veniam, quis nostru')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('um dolor sit amet, c', 'enderit in', 'iam, q')
     , ('s nisi ut', 'tion ulla', 'g elit, se')
     , ('eur si', 'ation ullamco ', 'm')
     , ('aliquip ex ea commodo con', 'u', 'minim veniam, quis nostrud exe')
     , ('nsequat. Duis aute iru', 'n reprehe', 'o laboris nisi ut aliqui')
     , ('ecat cupidat', 'ing', 'unt mollit anim id est l')
     , ('on proident, sunt in culpa', 'd', 'ulpa qui officia de')
     , ('ut labore et dolo', 'm ipsum dolor si', 'ip ex ')
     , ('do eiusmod tempor i', 'tet', 'e cillum dolore eu fugiat')
     , ('a pariatur. Excepteur ', 'exercitation ', ' cillum dolore e')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('na aliqu', ' reprehende', 'm dolore eu fugiat nulla p')
     , ('ci', 'enderit in volu', ' f')
     , ('ullamco laboris', 'q', 'epteur sint occaecat c')
     , ('x ea commodo co', 'la', 'nim ad minim v')
     , ('eu fugiat n', 'tur. Exc', 'rud exe')
     , ('orem ipsum dolor s', 'inim veniam', 'odo consequat. Dui')
     , ('nostrud ', 'n c', 'nisi ut aliquip ex ea commodo ')
     , (' sunt in culpa qui officia des', 'non proident, s', 'pariatur')
     , ('x e', 'serunt ', 't esse cillum dolore eu ')
     , ('ng elit', 'iam, quis n', 'at non pro')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('deserun', ', consectetur a', 'r in repr')
     , ('atio', 'velit esse c', 'enderit in voluptate')
     , ('didunt ut labore et dolore m', 'cita', 'adipi')
     , ('ecat cupidatat', 'prehe', 'nt ut ')
     , ('etur adipiscing eli', 'r in ', 'si ut aliquip ex ')
     , ('sum dolor', 'i', ' e')
     , ('pariatur. Excepteur s', 'exercitatio', 'uat. Duis aut')
     , ('ation ullamco l', ' pari', 'quat. Duis aute irure ')
     , ('equat. Duis aute irure d', 'r incididunt u', 'ad ')
     , ('ipiscing elit, sed do e', 'at null', 'labore et dolore magna al')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' labore et dolore ', 'culpa qui offici', 'olor in rep')
     , ('p ex ea commodo cons', 'a', 't esse cillum dolore eu fugiat')
     , ('prehenderit', 'cupidatat non pr', 'aliqua. Ut enim ad mini')
     , ('ecat cupidatat non proident, ', 'at. Duis ', ' aliqua. Ut e')
     , ('et, cons', 'ui ', 'co ')
     , ('it amet, consectetur adip', 'iscing eli', 'tation ullamco labo')
     , ('llit anim id est la', ' ', 't, conse')
     , ('occaecat cupidata', 'ur ', 'aecat c')
     , (' Ut enim ', 'ui', 't aliquip ex ea comm')
     , ('o consequ', 'dolor in rep', 'r in reprehe')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('e e', 't labore et do', 're magna aliqua. Ut enim')
     , ('epteur sint oc', ' Ut e', 'id est laborum.Lorem')
     , ('met, consectetur adipi', ' exercitation ', 're eu fugiat nulla pariatu')
     , ('ia deserunt mollit an', ' qui officia de', 'deserunt mollit a')
     , ('od tempor incididunt ut', 'unt ', ' magna aliqua. Ut')
     , ('a c', 'nulla pariatur. ', 'str')
     , ('lpa qui officia deserun', 'ecat cupidatat', 'o')
     , ('b', 't aliquip e', '. Duis aute irure dolor')
     , (' aliquip ex ', 'n reprehenderi', 'it amet, consec')
     , ('erit in voluptate v', 'strud exerc', 'do consequat. Duis aute')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('odo consequat. Dui', 'magna aliqu', 't amet, consectetur adi')
     , ('lamco laboris nisi ut aliqui', 'na aliqua. Ut', 'nulla pariatur. Excepteur s')
     , ('icia deserunt mollit anim ', ' magna ', 'p ex ea commodo consequat')
     , ('rum.Lorem ipsum dol', 'unt moll', 'u fugiat nulla')
     , ('amet, ', 's aute irur', 'commodo consequat. Duis ')
     , ('itation ulla', 'n pr', 'at nulla pariatur')
     , ('minim veniam, quis nostrud ex', 'incididunt', 'didunt ut labore et dolore')
     , ('fficia deseru', ' veniam, quis n', 'sit amet, ')
     , ('m veniam, quis nostrud ', 'llamco ', 'sit ')
     , ('nt ut labore et ', 'r', ' nostrud exercitation')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' cil', 'nim id est labor', '. Ut enim ad minim v')
     , ('onsequat. Dui', 't, sunt in ', 'pteur sint occae')
     , ('pariatur. Excep', 'ut aliquip ex e', ', consectetur adipi')
     , (' ad minim veniam, quis no', 'ulpa qui offic', 'int occaecat cupidatat no')
     , ('o consequat. Duis aute irure ', 'is n', ' Excepteur sint occaec')
     , (', quis no', 'p', ' dolor sit am')
     , ('t, consectetur adi', 'im ad minim ve', 'tat non proident, sunt in cu')
     , (' aliqua. Ut ', 'n ullamco', 'ea commodo consequa')
     , ('dolor sit amet, consectetur ad', 's nisi ut', ' non proi')
     , ('tur. Excepteur sint occ', ' tempor ', ' dolor in reprehenderit i')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('aborum.Lor', 'quat. Dui', ' sunt in culpa qui off')
     , ('ip ex ea commodo c', 'e velit esse cil', ' et dolore')
     , ('ulla pariatur.', 'or', 'amco laboris nisi ut aliquip')
     , ('t mollit anim id es', 'ui officia dese', 'riatur. Excepteur si')
     , (' ut labore et', 'nt in culp', 'lor')
     , ('cing', ' anim id est', 'int occaecat cupidatat non pr')
     , ('lit ess', 'e veli', 'tation ullamco laboris nisi')
     , ('oll', 'isi u', ' ullam')
     , ('fugiat', 'n', ' exercit')
     , ('boris nisi ut aliqui', 'prehenderit i', 'at ')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('ostrud exercitation ull', 'do co', 'nderit in ')
     , ('did', ' eiusmod t', 'or sit amet, consectetur adip')
     , ('commodo ', ' commodo conseq', 'nim ')
     , ('nim ', 'olor in repre', ' Ut enim ad minim venia')
     , ('unt in culpa qui offici', 'is a', 'ncididunt ut labore et')
     , (' consequat. Duis aute irure ', 'ation ul', 'laborum.')
     , ('pariatur. Excepteur sint', ' ', 'p ex ea commod')
     , ('iat nulla pariatu', 'is aute irure do', 'p ex ea commodo consequa')
     , ('lit anim id est laborum.', 'm id est labo', 'abore et d')
     , ('i', 'ur. E', 'tetur adipiscin')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' esse cillum dolore eu fugi', 'onsec', 'por incididunt u')
     , (' culpa qu', 'at cupidatat no', ' culpa qui officia des')
     , ('or', 'lor sit ', 'd tempor incididunt ut labore ')
     , ('laborum.L', 'r incid', 'sc')
     , ('t occaecat cupidata', ' adipiscin', ' in culpa qui officia deser')
     , ('in voluptate velit ess', 'or in repr', 'cupidatat non proident,')
     , ('iat nulla pariatur. Excep', 'ore', ' nisi ut aliquip ex ')
     , ('o laboris nisi ut aliquip ex', 'am', ' in reprehenderi')
     , ('t dolore magna aliq', ' enim ad minim ', 'ing elit, se')
     , ('aliqua. Ut enim ad', 'aliquip ex', 'cita')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('consectetur ', 'ipisci', ' dolore eu fugiat ')
     , (' nostrud exercitation ulla', 'qui o', 'oris n')
     , ('ute irure dol', 'iqua. Ut en', 'unt mollit anim id est labo')
     , (' eu fugiat null', 't in cul', ' dolor in reprehenderit ')
     , ('strud exercitation', ' minim veniam', 'im ven')
     , (' dolore eu fugiat nulla par', 'lore ', ' ipsum dolor si')
     , ('smod t', 'epteur sint ', 'llamco laboris nisi ut al')
     , ('e velit esse', 't d', 'proident, ')
     , ('on ullamco labo', ' commodo c', 'dolore e')
     , ('t enim ad minim veniam, qu', 'u', 'cing elit, sed do eiusmod temp')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('im id est l', 'a qui officia ', '.Lorem ipsum d')
     , ('q', ' eiusmod tempor ', 'atat')
     , ('officia deserunt mollit', 'ol', 'magna ali')
     , ('ation ullamco laboris nisi ut', 'nt ut labore e', ' ad mi')
     , ('ctetu', 't', 't, sed do eiusmod tempo')
     , ('an', ' in volupta', 'at non proident, sunt in cu')
     , (' q', ' dolor sit amet,', ' eiusmod tempor inci')
     , (' velit esse cillum dolor', 'dolor', 'psum dolor')
     , ('uip ex ea c', 'ut la', 'derit in voluptate velit esse ')
     , ('it,', 'tate velit ', 'oluptate velit esse c')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES (' in culpa qui of', 'illum dolore', 'sint occaecat cupid')
     , ('elit esse cillum dolore e', 'iqua. Ut ', 'deserunt ')
     , ('lor in reprehe', 'n ', 'ommodo consequat. Duis aute i')
     , ('sequat. Duis aute irur', 'um dolore ', ' sed do eiusmod tempo')
     , ('etur adipiscing elit, se', 'exer', 'icia deserunt mollit anim id e')
     , ('labore et dolore magna ali', 'ullam', 'ing elit, sed')
     , ('culpa qui officia deserunt mo', 'idunt ut labo', 'incididunt ut labore et do')
     , ('Ut enim ad minim veniam', 'riatur. Excepteu', 'it anim id est lab')
     , ('Duis', 'magn', ' mollit anim id e')
     , ('tur. Excepteur sint occaecat', 'mmod', 'illum dolore eu fugiat nulla p')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('n reprehenderit in volu', 'data', 'ommodo ')
     , ('ure dolor in reprehenderit in', 't ut ', 'modo consequat. Duis aute irur')
     , ('o laboris nisi ut ali', 'tempor incididu', 'p ex ea commodo conse')
     , ('riatur. Excepteur ', 'te v', 'm veniam, quis no')
     , ('rehenderit in voluptate vel', ' cil', 'tate ')
     , ('d do eiusmo', 'ectetur adip', ' magna aliqua. Ut enim ad mi')
     , (' ', 'idatat non proid', 'ut aliq')
     , ('iam,', ' aliquip ex e', 'nsequat')
     , ('trud exercitation', 'ficia deserunt ', 'tempor incididunt ut labore e')
     , ('t anim id est laborum.L', 'etur adipis', 'iqua. ')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('n voluptate velit ess', 'aborum.L', 'citation ullamco')
     , ('nderit in voluptate v', 'ia de', 'abore')
     , ('ia deserunt mollit ani', 'lit esse cillum ', 'n culpa qui')
     , ('mmodo ', 's nisi ut aliq', 'uat. Duis au')
     , ('ua. Ut enim ad minim venia', 'rud exercitation', ' esse cillum dolore e')
     , ('olo', 'xe', 'te velit esse cill')
     , ('ulla', '. Ut enim a', 'nt mollit ani')
     , ('rure dol', 'ehenderit in', 'n culpa qui officia ')
     , ('a qui officia deseru', 'xcepteur sint ', 'dent, sunt in culpa qui')
     , (' ex e', ' in cul', 'nderit in voluptate velit e')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('a qui officia des', ' minim veniam, q', 'm, qui')
     , ('iam, quis nostrud exerci', 'o', 'ui o')
     , (' nulla pariatur. Excepteu', 'iqua. Ut e', 'mollit anim i')
     , (' do', 'tate velit ess', 're eu fugiat nulla')
     , ('pa qui', 'te ve', 'u')
     , (' Ut enim ad mini', 't laborum.Lor', 'on proident, ')
     , ('fficia deserunt mollit anim id', ' aliqua. U', 'onsectetur adipiscing ')
     , ('re ', 'ugiat nu', 'cillum dolore eu')
     , ('ididunt ut labore et dolo', 'ui officia ', ' n')
     , (' laboris nisi ut aliq', ' occa', 'ugia')
;
INSERT INTO bookstoredb.users (email, password, full_name)
VALUES ('at non proident, sunt in', 'olore eu ', 'oris nisi u')
     , ('ent, sunt in culp', 'el', ' deserunt mollit')
;